# -*- coding: utf-8 -*-

# Scrapy settings for tickets project
#
# For simplicity, this file contains only the most important settings by
# default. All the other settings are documented here:
#
#     http://doc.scrapy.org/en/latest/topics/settings.html
#

BOT_NAME = 'ChinaAir'

SPIDER_MODULES = ['tickets.spiders']
NEWSPIDER_MODULE = 'tickets.spiders'

ITEM_PIPELINES = {
    "tickets.pipelines.BackpackersPipeline": 11
}

DUPEFILTER_CLASS = 'tickets.duplicated_filter.SeenURLFilter'

DOWNLOAD_DELAY = 2

BACKPACKERSSPIDER_EUROPE="CPH,MOW,BUD,VIE,ATH,FRA,BER,CGN,DUS,HAM,MUC,OSL,PRG,BRU,PAR,LYS,STO,GVA,ZRH,LUX,ROM,MIL,VCE,HEL,LON,BHX,MAN,AMS,LIS,MAD,BCN"
BACKPACKERSSPIDER_NEWZEALAND="SPN,ROR,NAN,BNE,MEL,PER,SYD,ADL,CBR,CNS,OOL,AKL,CHC,WLG,GUM"
BACKPACKERSSPIDER_JAPAN="OSA,SPK,TYO,FSZ,FUK,HIJ,HKD,KMI,KOJ,NGO,OKA,SDJ,TOY"
BACKPACKERSSPIDER_KOREA="SEL,CJU,PUS"

FUNTIMESPIDER_NEWZEALAND_COUNTRY="CN_NEW+ZEALAND"
FUNTIMESPIDER_NEWZEALAND_CITY="CHC,WLG,WLG,ZQN"
FUNTIMESPIDER_NEWZEALAND_REGION="RE_OCEANIA"

FUNTIMESPIDER_AUSTRALIA_COUNTRY="CN_AUSTRALIA"
FUNTIMESPIDER_AUSTRALIA_CITY="SPN,ROR,NAN,BNE,MEL,PER,SYD,ADL,CBR,CNS,OOL,WLG,GUM,DRW"
FUNTIMESPIDER_AUSTRALIA_REGION="RE_OCEANIA"

FUNTIMESPIDER_ENGLAND_COUNTRY=""
FUNTIMESPIDER_EUROPE_CITY="LON,BHX,MAN,EDI,PAR,LYS,NCE,MRS,FRA,BER,MUC,AMS,ROM,VCE,MIL,FLR,ZRH,GVA,MAD,BCN,VIE,BRU,PRG,CPG,ATH,MOW,LED,BUD,STO,HEL,OSL,LIS,DUB"
FUNTIMESPIDER_EUPOPE_REGION=""

FUNTIMESPIDER_ENGLAND_COUNTRY="CN_ENGLAND"
FUNTIMESPIDER_ENGLAND_CITY="LON,BHX,MAN,EDI"
FUNTIMESPIDER_ENGLAND_REGION="RE_EUROPE"

FUNTIMESPIDER_FRANCE_COUNTRY="CN_FRANCE"
FUNTIMESPIDER_FRANCE_CITY="PAR,LYS,NCE,MRS"
FUNTIMESPIDER_FRANCE_REGION="RE_EUROPE"

FUNTIMESPIDER_GERMANY_COUNTRY="CN_GERMANY"
FUNTIMESPIDER_GERMANY_CITY="FRA,BER,MUC"
FUNTIMESPIDER_GERMANY_REGION="RE_EUROPE"

FUNTIMESPIDER_HOLLAND_COUNTRY="CN_HOLLAND"
FUNTIMESPIDER_HOLLAND_CITY="AMS"
FUNTIMESPIDER_HOLLAND_REGION="RE_EUROPE"

FUNTIMESPIDER_ITALY_COUNTRY="CN_ITALY"
FUNTIMESPIDER_ITALY_CITY="ROM,VCE,MIL,FLR"
FUNTIMESPIDER_ITALY_REGION="RE_EUROPE"

FUNTIMESPIDER_SWITZERLAND_COUNTRY="CN_SWITZERLAND"
FUNTIMESPIDER_SWITZERLAND_CITY="ZRH,GVA"
FUNTIMESPIDER_SWITZERLAND_REGION="RE_EUROPE"

FUNTIMESPIDER_SPANISH_COUNTRY="CN_SPANISH"
FUNTIMESPIDER_SPANISH_CITY="MAD,BCN"
FUNTIMESPIDER_SPANISH_REGION="RE_EUROPE"

FUNTIMESPIDER_AUSTRIA_COUNTRY="CN_AUSTRIA"
FUNTIMESPIDER_AUSTRIA_CITY="VIE"
FUNTIMESPIDER_AUSTRIA_REGION="RE_EUROPE"

FUNTIMESPIDER_BELGIUM_COUNTRY="CN_BELGIUM"
FUNTIMESPIDER_BELGIUM_CITY="BRU"
FUNTIMESPIDER_BELGIUM_REGION="RE_EUROPE"

FUNTIMESPIDER_CZECH_COUNTRY="CN_CZECH"
FUNTIMESPIDER_CZECH_CITY="PRG"
FUNTIMESPIDER_CZECH_REGION="RE_EUROPE"

FUNTIMESPIDER_DENMARK_CITY="CN_DENMARK"
FUNTIMESPIDER_DENMARK_CITY="CPH"
FUNTIMESPIDER_DENMAR_REGION="RE_EUROPE"

FUNTIMESPIDER_GREECE_COUNTRY="CN_GREECE"
FUNTIMESPIDER_GREECE_CITY="ATH"
FUNTIMESPIDER_GREECE_REGION="RE_EUROPE"

FUNTIMESPIDER_RUSSIA_COUNTRY="CN_RUSSIA"
FUNTIMESPIDER_RUSSIA_CITY="MOW,LED"
FUNTIMESPIDER_RUSSIA_REGION="RE_EUROPE"

FUNTIMESPIDER_HUNGARY_COUNTRY="CN_HUNGARY"
FUNTIMESPIDER_HUNGARY_CITY="BUD"
FUNTIMESPIDER_HUNGARY_REGION="RE_EUROPE"

FUNTIMESPIDER_SWEDEN_COUNTRY="CN_SWEDEN"
FUNTIMESPIDER_SWEDEN_CITY="STO"
FUNTIMESPIDER_SWEDEN_REGION="RE_EUROPE"

FUNTIMESPIDER_FINLAND_COUNTRY="CN_FINLAND"
FUNTIMESPIDER_FINLAND_CITY="HEL"
FUNTIMESPIDER_FINLAND_REGION="RE_EUROPE"

FUNTIMESPIDER_NORWAY_COUNTRY="CN_NORWAY"
FUNTIMESPIDER_NORWAY_CITY="OSL"
FUNTIMESPIDER_NORWAY_REGION="RE_EUROPE"

FUNTIMESPIDER_PORTUGAL_COUNTRY="CN_PORTUGAL"
FUNTIMESPIDER_PORTUGAL_CITY="LIS"
FUNTIMESPIDER_PORTUGAL_REGION="RE_EUROPE"

FUNTIMESPIDER_IRELAND_COUNTRY="CN_IRELAND"
FUNTIMESPIDER_IRELAND_CITY="DUB"
FUNTIMESPIDER_IRELAND_REGION="RE_EUROPE"

FUNTIMESPIDER_JAPAN_COUNTRY="CN_JAPAN"
FUNTIMESPIDER_JAPAN_CITY="OSA,SPK,TYO,FSZ,FUK,HIJ,HKD,KMI,KOJ,NGO,OKA,SDJ,TOY,AKJ,HIJ,ISG,KIJ,KMQ,KUH,NGS,OKJ,TAK"
FUNTIMESPIDER_JAPAN_REGION="RE_ASIA_N"

FUNTIMESPIDER_KOREA_COUNTRY="CN_KOREA"
FUNTIMESPIDER_KOREA_CITY="SEL,CJU,PUS"
FUNTUNESPIDER_KOREA_CITY="RE_ASIS_N"

CHINAAIRLINESPIDER_FROM_CITY="TPE"
CHINAAIRLINESPIDER_TO_CITY="KIX,SUB,SGN,HND,PEN,HKG,RDU,GMP,PUS,TAK,KOJ,KMI,CTS,MFM,ISG,NRT,NGO,MNL,KUL,CGK,BKK,ICN,HIJ,HAN,FUK,DPS,DEL,FSZ,TOY,SIN,PNH,OKA,RGN"
#CHINAAIRLINESPIDER_TO_CITY="KIX"
CHINAAIRLINESPIDER_CABINCLASS="Y"
#CHINAAIRLINESPIDER_DATE="7,14,21,30,45,60,90,120,150,180"
CHINAAIRLINESPIDER_DATE="180"
CHINAAIRLINESPIDER_WEEK="7"

# Crawl responsibly by identifying yourself (and your website) on the user-agent
#USER_AGENT = 'happy_newyear (+http://www.happynewyear.com)'

BOT_NAME = "happynewyear"
